# Generated by Django 4.1.5 on 2023-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='audio',
            field=models.FileField(upload_to='albums'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
