# Generated by Django 4.1.5 on 2023-02-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_options_alter_song_options_song_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
    ]
