# Generated by Django 4.1.5 on 2023-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_audio_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='album',
            name='audio',
            field=models.FileField(upload_to='media/albums'),
        ),
    ]
