# Generated by Django 4.1.5 on 2023-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_description_alter_album_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='media/albums_icon', verbose_name='Фото'),
        ),
    ]
