# Generated by Django 4.1.5 on 2023-02-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_album', to='music.artist'),
        ),
    ]
