# Generated by Django 4.1.5 on 2023-02-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_review_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='artist',
        ),
        migrations.AddField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist', to='music.artist'),
        ),
    ]
