# Generated by Django 4.1.5 on 2023-02-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_audiofile_review_album_alter_review_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
    ]
