# Generated by Django 4.1.5 on 2023-02-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_review_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
    ]
