# Generated by Django 4.1.5 on 2023-02-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_rename_created_album_release_remove_album_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
    ]
