# Generated by Django 4.1.5 on 2023-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_audiofile_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.AlterField(
            model_name='review',
            name='audio',
            field=models.ManyToManyField(blank=True, to='music.attachment'),
        ),
    ]
