# Generated by Django 4.1.5 on 2023-02-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_attachment_delete_audiofile_alter_review_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='audio',
        ),
        migrations.AddField(
            model_name='review',
            name='file',
            field=models.FileField(default=0, upload_to='media/audio_files'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
