# Generated by Django 4.1.5 on 2023-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_alter_review_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.ManyToManyField(to='music.genre'),
        ),
    ]
