# Generated by Django 4.1.5 on 2023-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release',
            field=models.DateTimeField(),
        ),
    ]
